### ISSUE TITLE
Potential Solar Radiation Confusion

### ISSUE THREAD

**Issue by ckaros** [kristianfoerster/melodist#5]
I am wondering if there is an error in the potential solar radiation function.  The following lines are meant to account for scattering and direct radiation:

`# compute transmissivities for direct and diffus radiation using cloud fraction
transmissivity_direct = (0.6 + 0.2 * cos_solar_zenith) * (1.0 - cloud_fraction)
transmissivity_diffuse = (0.3 + 0.1 * cos_solar_zenith) * cloud_fraction`

I check the [reference document for this routine](https://www.fs.fed.us/rm/pubs_other/rmrs_2006_liston_g002.pdf) and the equation look more like this:

`# compute transmissivities for direct and diffus radiation using cloud fraction
transmissivity_direct = (0.6 - 0.2 * cos_solar_zenith) * (1.0 - cloud_fraction)
transmissivity_diffuse = (0.3 - 0.1 * cos_solar_zenith) * cloud_fraction`

Was this done purposefully to account for some phase shift specific to this code? Or is this an an error?

Additionally, I found an important bug on lines 146 and 147:

`direct_radiation = (solar_constant_times_radius_ratio * transmissivity_direct) * np.cos(solar_zenith_angle)`

`diffuse_radiation = solar_constant_times_radius_ratio * transmissivity_diffuse # * np.cos(solarZenitAngle)#?` 

It is the diffuse_radiation that should be multiplied by the zenith angle not the direct. The direct radiation is multiplied by a land slope if given. This bug produces very small potential radiation values and needs to be fixed.

**Comment by fhanzer** [comment]
Hi @ckaros, first of all thanks for raising this issue and sorry for the (very) late reply!

With regard to your first point (confusion of using `+` or `-` in calculating the transmissivities) we believe that this is an error in the [Liston and Elder (2006)](https://www.fs.fed.us/rm/pubs_other/rmrs_2006_liston_g002.pdf) reference and that in both equations actually a `+` should be used (as done in MELODIST), as otherwise the obtained radiation values are unrealistically low. While we were not able to obtain the original reference to these equations (Burridge and Gadd 1974), other references citing them (e.g., [Stull (1988)](https://doi.org/10.1007/978-94-009-3027-8), [Mensink and de Ridder (2000)](https://doi.org/10.1504/ijep.2000.000578), [Jegede et al. (2011)](https://doi.org/10.1080/14786450600593261)) seem to confirm that the `+` form is correct.

Regarding your second comment (calculation of direct and diffuse radiation) - yes, this indeed a bug. This was fixed in 965ed73b0f86b8d0b1f54dcdfd51c999bfdf48b5. Thank you!
