### ISSUE TITLE
AttributeError: 'DatetimeIndex' object has no attribute 'is_all_dates'

### ISSUE THREAD

**Issue by Freestyleyang** [kristianfoerster/melodist#8]
Hi There,

Thank you for developing such a great package for climate variables disaggregation.

I have followed the "examples.ipynb", however, an error occurs when I try to run "**_station = melodist.Station(lon=longitude, lat=latitude, timezone=timezone, data_daily=data_obs_daily)_**". It shows "**AttributeError: 'DatetimeIndex' object has no attribute 'is_all_dates'**". Could you please help me with this issue? I am running Python 3.11.3, thank you.

![Error](https://github.com/kristianfoerster/melodist/assets/20953347/0705124d-a17a-43b7-873a-2e2098a37342)

**Comment by jackwarden-eng** [comment]
Hey I just dealt with this issue today. Pandas got rid of this attribute at some point. I have made this work by using pandas 1.0.5 which requires you to use older versions of numpy, xarray etc. Numpy 1.21.4 and Xarray 0.18.1 are compatible with this pandas version.

**Comment by fhanzer** [comment]
Thanks! This issue should now also be fixed by the latest commits (see the discussion [here](#7)). We will publish a new release soon; in the meantime you could install the version from GitHub (`pip install --force-reinstall --no-deps git+https://github.com/kristianfoerster/melodist.git`) if you want to use more recent pandas versions.

**Comment by fhanzer** [comment]
Ok, we have just released the new version 0.1.5 on PyPI. Let us know if there are any issues!
